import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { FeedbackProvider } from "@/context/FeedbackContext";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Feedback USA",
  description: "Generated by Memento Design",
  icons: {
    icon: "/icons/sa-favicon-black.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} w-full flex items-center justify-center`}
      >
        <FeedbackProvider>{children}</FeedbackProvider>
      </body>
    </html>
  );
}
